extension:        "crml"
use_cache:        true
cache_dir:        "../Cache"
comment_symbol:   "#"
show_comments:    false
block_comments:   false
variable_symbol:  "$"
left_delimiter:   "{"
right_delimiter:  "}"
file_header:      "Caramel template engine."
