index:
  name: Overview
  folder: /

docs:
  parent: index
  name: documentation
  folder: docs/

config:
  parent: docs
  name: documentation
  folder: /docs/config

template hirachy:
  parent: docs
  name: documentation
  folder: /docs/template_hirachy

adding languages:
  parent: docs
  name: documentation
  folder: /docs/adding_languages

examples:
  parent: index
  name: examples
  folder: /examples

